services:
  app:
    # jika ingin menggunakan image yang sudah saya buat
    # image: ekasatriaap/apc:5.6
    build:
      context: .
      dockerfile: ./docker-compose/php/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker-compose/apache:/etc/apache2/sites-available
    networks:
      - app-network

  mariadb:
    image: mariadb
    container_name: mariadb-app
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - app-db:/var/lib/mysql
    networks:
      - app-network

volumes:
  app-db:
    name: volume-app-db

networks:
  app-network:
    driver: bridge
